// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hospital_reservation_system.Data;

#nullable disable

namespace hospital_reservation_system.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251215121722_SecondCreatations")]
    partial class SecondCreatations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("hospital_reservation_system.Data.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("UserId");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("hospital_reservation_system.Data.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dr. Ahmed"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dr. Sara"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dr. Wed"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dr. Mohammed"
                        });
                });

            modelBuilder.Entity("hospital_reservation_system.Data.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("timeSlot");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Time = "3:30"
                        },
                        new
                        {
                            Id = 2,
                            Time = "14:45"
                        },
                        new
                        {
                            Id = 3,
                            Time = "10:30"
                        },
                        new
                        {
                            Id = 4,
                            Time = "13:00"
                        },
                        new
                        {
                            Id = 5,
                            Time = "18:00"
                        },
                        new
                        {
                            Id = 6,
                            Time = "20:15"
                        },
                        new
                        {
                            Id = 7,
                            Time = "21:00"
                        });
                });

            modelBuilder.Entity("hospital_reservation_system.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAdmin = false,
                            UserName = "patient1"
                        },
                        new
                        {
                            Id = 2,
                            IsAdmin = false,
                            UserName = "patient2"
                        },
                        new
                        {
                            Id = 3,
                            IsAdmin = false,
                            UserName = "patient3"
                        },
                        new
                        {
                            Id = 4,
                            IsAdmin = false,
                            UserName = "patient4"
                        },
                        new
                        {
                            Id = 5,
                            IsAdmin = true,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("hospital_reservation_system.Data.Appointment", b =>
                {
                    b.HasOne("hospital_reservation_system.Data.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hospital_reservation_system.Data.TimeSlot", "Time")
                        .WithMany()
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hospital_reservation_system.Data.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId");

                    b.Navigation("Doctor");

                    b.Navigation("Time");

                    b.Navigation("User");
                });

            modelBuilder.Entity("hospital_reservation_system.Data.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("hospital_reservation_system.Data.User", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
